const BIRDS = [
  {
    id: 1,
    name: "Serçe",
    englishName: "House Sparrow",
    emoji: "🐦",
    color: "#c8a96e",
    habitat: "Şehir",
    difficulty: "Kolay",
    description: "Şehirlerde en çok görülen kuşlardan biridir. Küçük, kahverengi tüylü ve çok neşeli bir kuştur!",
    funFact: "Serçeler birlikte toz banyosu yapmaktan çok hoşlanır! Toprağa yuvarlana yuvarlana temizlenirler.",
    sound: "Cik cik cik!",
    size: "Küçük",
    season: "Tüm yıl"
  },
  {
    id: 2,
    name: "Güvercin",
    englishName: "Pigeon",
    emoji: "🕊️",
    color: "#a0a0b0",
    habitat: "Şehir",
    difficulty: "Kolay",
    description: "Meydanlarda ve parklarda sıkça görülür. Gri-mavi tüyleri ve yeşil-mor boyun rengiyle çok güzeldir.",
    funFact: "Güvercinler eve geri dönme konusunda inanılmazdır. Yüzlerce kilometre uzaktan bile yuvasını bulabilirler!",
    sound: "Guu guu guu!",
    size: "Orta",
    season: "Tüm yıl"
  },
  {
    id: 3,
    name: "Karatavuk",
    englishName: "Blackbird",
    emoji: "🐦‍⬛",
    color: "#333333",
    habitat: "Park / Bahçe",
    difficulty: "Kolay",
    description: "Erkekleri simsiyah tüylere ve turuncu gagaya sahiptir. Dişileri kahverengidir. Şarkıları çok güzeldir!",
    funFact: "Karatavuklar sabahın erken saatlerinde en güzel şarkılarını söyler. Bu yüzden 'şafak korosu'nun yıldızlarıdır!",
    sound: "Fıs fıs vit vit!",
    size: "Orta",
    season: "Tüm yıl"
  },
  {
    id: 4,
    name: "Baştankara",
    englishName: "Great Tit",
    emoji: "🐤",
    color: "#ffd700",
    habitat: "Orman / Bahçe",
    difficulty: "Orta",
    description: "Sarı göğsü, siyah başı ve beyaz yanakları olan çok şirin bir kuştur. Çekirdek yemeyi çok sever!",
    funFact: "Baştankaralar çok akıllıdır! Kapakları açmayı ve zor yerlerdeki yiyecekleri bulmayı öğrenebilirler.",
    sound: "Ti-ti-ti-tis!",
    size: "Küçük",
    season: "Tüm yıl"
  },
  {
    id: 5,
    name: "Sakarca Kazı",
    englishName: "Greylag Goose",
    emoji: "🪿",
    color: "#8b7355",
    habitat: "Göl / Nehir",
    difficulty: "Kolay",
    description: "Büyük ve gürültülü bir kuştur. Gölde ailesiyle birlikte yüzerken görmek çok güzeldir!",
    funFact: "Kazlar ömür boyu tek bir eşle yaşar. Ailelerine çok bağlıdırlar ve yavrularını korumak için çok cesurdurlar!",
    sound: "Vak vak vak!",
    size: "Büyük",
    season: "Tüm yıl"
  },
  {
    id: 6,
    name: "Leylek",
    englishName: "White Stork",
    emoji: "🦢",
    color: "#ffffff",
    habitat: "Köy / Tarla",
    difficulty: "Orta",
    description: "Uzun bacakları ve kırmızı gagasıyla gökyüzünde süzülür. Her yıl Afrika'ya göç eder ve geri döner!",
    funFact: "Leylekler yuvalarını her yıl aynı yere yapar ve yuvayı büyütürler. Bazı yuvalar yüzlerce yıl kullanılır!",
    sound: "Tak tak tak! (gagasını şaklatır)",
    size: "Büyük",
    season: "İlkbahar / Yaz"
  },
  {
    id: 7,
    name: "Kırlangıç",
    englishName: "Barn Swallow",
    emoji: "🐦",
    color: "#1a237e",
    habitat: "Her yer",
    difficulty: "Orta",
    description: "Havada çok hızlı uçar ve böcek yer. Çatal kuyruğu ve mavi-kırmızı renkleriyle çok şıktır!",
    funFact: "Kırlangıçlar hem yiyip içer hem de uyurken uçabilirler! Yere hiç inmeden günlerce havada kalabilirler.",
    sound: "Tivit tivit tivit!",
    size: "Küçük",
    season: "İlkbahar / Yaz"
  },
  {
    id: 8,
    name: "Atmaca",
    englishName: "Sparrowhawk",
    emoji: "🦅",
    color: "#795548",
    habitat: "Orman",
    difficulty: "Zor",
    description: "Çok hızlı ve becerikli bir avcıdır. Keskin gözleri ve kısa kanatlarıyla ormanlarda av yapar.",
    funFact: "Atmacalar saatte 50 km hızla uçabilir ve havada ani dönüşler yapabilir. Gerçek bir akrobat!",
    sound: "Ki ki ki!",
    size: "Orta",
    season: "Tüm yıl"
  },
  {
    id: 9,
    name: "Saka",
    englishName: "Goldfinch",
    emoji: "🐦",
    color: "#ff6f00",
    habitat: "Bahçe / Tarla",
    difficulty: "Orta",
    description: "Kırmızı yüzü, sarı kanat bantları ve siyah-beyaz deseniyle çok renkli bir kuştur. Gerçek bir güzellik!",
    funFact: "Sakalar devedikeni tohumlarını yemeyi çok sever. İnce gagasıyla tohumları ustaca çıkarabilirler.",
    sound: "Tvitvit tvitvit!",
    size: "Küçük",
    season: "Tüm yıl"
  },
  {
    id: 10,
    name: "Baykuş",
    englishName: "Owl",
    emoji: "🦉",
    color: "#6d4c41",
    habitat: "Orman / Bahçe",
    difficulty: "Çok Zor",
    description: "Gece aktif olan gizemli bir kuştur. Büyük yuvarlak gözleri her şeyi karanlıkta görür!",
    funFact: "Baykuşlar başlarını neredeyse 270 derece döndürebilir! Ama gözlerini hareket ettiremezler, bunun yerine başlarını çevirirler.",
    sound: "Hu hu hu!",
    size: "Orta",
    season: "Tüm yıl"
  },
  {
    id: 11,
    name: "Martı",
    englishName: "Seagull",
    emoji: "🐦",
    color: "#e0e0e0",
    habitat: "Deniz / Göl",
    difficulty: "Kolay",
    description: "Deniz kıyılarında ve göllerde yaşar. Beyaz tüyleri ve sarı gagasıyla kolay tanınır.",
    funFact: "Martılar içtikleri tuzlu deniz suyunu burunlarındaki özel bezlerle süzerek tuzunu atabilirler!",
    sound: "Meyav meyav!",
    size: "Orta",
    season: "Tüm yıl"
  },
  {
    id: 12,
    name: "Papağan",
    englishName: "Parrot",
    emoji: "🦜",
    color: "#4caf50",
    habitat: "Tropikal Orman",
    difficulty: "Zor",
    description: "Renkli tüyleri ve insan sesi taklit etme yeteneğiyle çok özel bir kuştur!",
    funFact: "Papağanlar sadece sesleri taklit etmez, bazıları kelimelerin anlamını da öğrenebilir ve doğru bağlamda kullanabilir!",
    sound: "Merhaba! Merhaba!",
    size: "Orta",
    season: "Tüm yıl"
  }
];

const BADGES = [
  { id: "first_sighting", name: "İlk Gözlem!", emoji: "⭐", description: "İlk kuşunu gözlemledin!", condition: (sightings) => sightings.length >= 1 },
  { id: "five_sightings", name: "Meraklı Gözlemci", emoji: "🔭", description: "5 kuş gözlemledin!", condition: (sightings) => sightings.length >= 5 },
  { id: "ten_sightings", name: "Kuş Dostu", emoji: "🐦", description: "10 kuş gözlemledin!", condition: (sightings) => sightings.length >= 10 },
  { id: "five_species", name: "Keşifçi", emoji: "🗺️", description: "5 farklı tür gözlemledin!", condition: (sightings) => new Set(sightings.map(s => s.birdId)).size >= 5 },
  { id: "all_species", name: "Uzman Ornitolog", emoji: "🏆", description: "Tüm kuşları gözlemledin!", condition: (sightings) => new Set(sightings.map(s => s.birdId)).size >= BIRDS.length },
  { id: "early_bird", name: "Erken Kuş", emoji: "🌅", description: "Sabah 7'den önce gözlem yaptın!", condition: (sightings) => sightings.some(s => { const h = new Date(s.date).getHours(); return h < 7; }) },
  { id: "night_owl", name: "Gece Kuşu", emoji: "🌙", description: "Akşam 20'den sonra gözlem yaptın!", condition: (sightings) => sightings.some(s => { const h = new Date(s.date).getHours(); return h >= 20; }) },
  { id: "hard_bird", name: "Cesur Avcı", emoji: "🦅", description: "Zor bir kuş gözlemledin!", condition: (sightings) => sightings.some(s => { const b = BIRDS.find(b => b.id === s.birdId); return b && (b.difficulty === "Zor" || b.difficulty === "Çok Zor"); }) }
];
